function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 07-Apr-2016 14:51:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[190 1100]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Transmission %');

% Create xlabel
xlabel('Wavelength (nm)');

% Create title
title('Transmission Profile - Annealed 6YSZ Sample 9');

% Create plot
plot(X1,Y1);

