function HistFit(xvector1, yvector1, X1, Y1)
%CREATEFIGURE(XVECTOR1, YVECTOR1, X1, Y1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 07-Nov-2017 16:23:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.134122807017544 0.775 0.790877192982456]);
hold(axes1,'on');

% Create bar
bar(xvector1,yvector1,'BarWidth',1);

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[1 0 0]);

% Create xlabel
xlabel('Grain Size (nm)');

% Create title
title('Grain Size Distribution of 8YSZ');

% Create ylabel
ylabel('Frequency');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[77 111 145 179 213 247 281 315 349 383]);
% Create textbox
annotation(figure1,'textbox',...
    [0.730831973898859 0.776315789473684 0.146818923327895 0.0921052631578944],...
    'String',{'AGS = 183 nm'},...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FitBoxToText','off');

