function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 25-May-2016 16:50:18

% Create figure
figure1 = figure('Name','6%mol TbZrO2 - Freeze Dry Powder');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Enclosed','LineWidth',2);

% Create plot
plot(X2,Y2,'DisplayName','Dumped','LineWidth',2);

% Create xlabel
xlabel({'Time (s)',''},'FontWeight','bold');

% Create title
title('6%mol Tb:ZrO_{2}');

% Create ylabel
ylabel('Temperature (\circC)','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1200]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14,'FontWeight','bold','XGrid','on','XTick',...
    [0 50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000 1050 1100 1150 1200],...
    'YGrid','on');
% Create legend
legend(axes1,'show');

